package com.example.ui.theme

import androidx.compose.ui.graphics.Color

// Light Theme Palettes (Professional Polish, modern blue)
val ProfessionalPrimaryLight = Color(0xFF005FB0)
val ProfessionalOnPrimaryLight = Color(0xFFFFFFFF)
val ProfessionalPrimaryContainerLight = Color(0xFFD6E3FF)
val ProfessionalOnPrimaryContainerLight = Color(0xFF001B3D)
val ProfessionalSecondaryLight = Color(0xFF565E71)
val ProfessionalOnSecondaryLight = Color(0xFFFFFFFF)
val ProfessionalSecondaryContainerLight = Color(0xFFDAE2F9)
val ProfessionalOnSecondaryContainerLight = Color(0xFF131C2C)
val ProfessionalTertiaryLight = Color(0xFF705573)
val ProfessionalOnTertiaryLight = Color(0xFFFFFFFF)
val ProfessionalBackgroundLight = Color(0xFFF8F9FF)
val ProfessionalOnBackgroundLight = Color(0xFF1A1C1E)
val ProfessionalSurfaceLight = Color(0xFFF8F9FF)
val ProfessionalOnSurfaceLight = Color(0xFF1A1C1E)
val ProfessionalSurfaceVariantLight = Color(0xFFE1E2EC)
val ProfessionalOnSurfaceVariantLight = Color(0xFF43474E)
val ProfessionalOutlineLight = Color(0xFF74777F)
val ProfessionalOutlineVariantLight = Color(0xFFC4C6D0)
val ProfessionalErrorLight = Color(0xFFBA1A1A)

// Dark Theme Palettes (Midnight Professional Navy)
val ProfessionalPrimaryDark = Color(0xFFADC6FF)
val ProfessionalOnPrimaryDark = Color(0xFF002E5A)
val ProfessionalPrimaryContainerDark = Color(0xFF004684)
val ProfessionalOnPrimaryContainerDark = Color(0xFFD6E3FF)
val ProfessionalSecondaryDark = Color(0xFFBEC6DC)
val ProfessionalOnSecondaryDark = Color(0xFF283141)
val ProfessionalSecondaryContainerDark = Color(0xFF3E4759)
val ProfessionalOnSecondaryContainerDark = Color(0xFFDAE2F9)
val ProfessionalTertiaryDark = Color(0xFFDDBCE0)
val ProfessionalOnTertiaryDark = Color(0xFF3F2843)
val ProfessionalBackgroundDark = Color(0xFF111318)
val ProfessionalOnBackgroundDark = Color(0xFFE2E2E9)
val ProfessionalSurfaceDark = Color(0xFF111318)
val ProfessionalOnSurfaceDark = Color(0xFFE2E2E9)
val ProfessionalSurfaceVariantDark = Color(0xFF43474E)
val ProfessionalOnSurfaceVariantDark = Color(0xFFC4C6D0)
val ProfessionalOutlineDark = Color(0xFF8E9099)
val ProfessionalOutlineVariantDark = Color(0xFF43474E)
val ProfessionalErrorDark = Color(0xFFFFB4AB)
